maze_solver_node:
  ros__parameters:
    num_waypoints: -1             # (-1 all) waypoints
    odom_topic: "/odometry/filtered"
    laser_topic: "/scan"
    laser_flip: true
    laser_offset_deg: 180.0  # 0.0 / 180.0
    waypoint_file: "/home/user/ros2_ws/src/ROSBot_XL_mazesolver/resources/waypoints/sim_waypoints.yaml"

    # PID gain
    # Distance Controller
    DkP: 0.6
    DkI: 0.01
    DkD: 1.1
    # Turn Controller
    TkP: 3.0
    TkI: 0.0001
    TkD: 2.0

    max_ang_vel: 1.5

    odom_drift_threshold: 0.05  # 5cm
    yaw_tolerance: 0.01         # rad
    goal_tolerance: 0.02